### ISSUE TITLE
NER Spacy model

### ISSUE THREAD

**Issue by madewild** [madewild/tac#12]
Try fr_core_news_md instead of _sm because the results are quite poor with the smallest model

**Comment by devironl** [comment]
With Docker it brings to memory leaks. So I suggest we keep it as light as possible !

**Comment by madewild** [comment]
Keeping open to see if we can accommodate with larger docker...

**Comment by madewild** [comment]
Keeping open to see if we can accommodate with larger docker...

**Comment by devironl** [comment]
I have replaced the small model by the medium one and it works
