### ISSUE TITLE
Scraping example

### ISSUE THREAD

**Issue by devironl** [madewild/tac#47]
- [x] Which corpus for the exercises ?
- [x] Do we update notebooks ?
- [x] Do we update libraries ?
- [x] Which corpus tor the final project ?
- [x] Scraping archives le soir: bug (not consistent website ?)

**Comment by madewild** [comment]
I did not have much time but let's indeed discuss this tonight

**Comment by madewild** [comment]
@devironl what's the status with the scraping?
