### ISSUE TITLE
Add instructions for installing in Windows

### ISSUE THREAD

**Issue by devironl** [madewild/tac#49]

**Comment by devironl** [comment]
@madewild it's pushed on the refactoring branch. you can test if it works !
Thanks

**Comment by madewild** [comment]
```bash
PS C:\Users\Max\git\tac> Set-ExecutionPolicy RemoteSigned
Set-ExecutionPolicy : L'accès à la clé de Registre 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' est refusé. Pour modifier la stratégie d’exécution pour l’étendue par défaut (LocalMachine), démarrez Windows PowerShell avec l’option Exécuter en tant qu’administrateur. Pour 
modifier la stratégie d’exécution pour l’utilisateur actuel, exécutez «Set-ExecutionPolicy -Scope CurrentUser».
Au caractère Ligne:1 : 1
+ Set-ExecutionPolicy RemoteSigned
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

**Comment by madewild** [comment]
`Set-ExecutionPolicy -Scope CurrentUser RemoteSigned` fonctionne mais je ne sais pas si ce sera suffisant...

**Comment by madewild** [comment]
En plus de cocher la case pour le PATH, je propose d'utiliser custom install pour changer le chemin à la racine du C : C:\Python310

**Comment by madewild** [comment]
virtualenv : Le terme « virtualenv » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.

Il manque une ligne pour installer virtualenv : `pip install virtualenv`

**Comment by madewild** [comment]
PS C:\Users\Max\git\tac> pip install --upgrade pip
Requirement already satisfied: pip in c:\python310\lib\site-packages (22.2.2)

> pas indispensable si on veut simplifier

**Comment by madewild** [comment]
Il manque aussi cette ligne pour activer le venv : 

`.\tac_venv\Scripts\activate`

**Comment by madewild** [comment]
J'ai adapté le readme mais à présent j'ai ça : 

ERROR: Cannot install -r .\requirements.txt (line 7) and beautifulsoup4==4.11.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested beautifulsoup4==4.11.1
    textract 1.6.5 depends on beautifulsoup4~=4.8.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by devironl** [comment]
Based on the first course, it is clear enough. Thanks
