### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by madewild** [madewild/tac#52]
I renamed master to main to align with current best practices.

@devironl you may need to follow these steps:

# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main

**Comment by madewild** [comment]
When it's done on your side you can close this issue

**Comment by devironl** [comment]
Done :-) Thanks for the instructions
