### ISSUE TITLE
Give PDF examples (for pdf2text in s1_convert - module 2)

### ISSUE THREAD

**Issue by devironl** [madewild/tac#53]
the first part of the conversion notebook converts pdf to text
is there a possibility to provide the students with the pdf corpus also ?

**Comment by madewild** [comment]
I can give a few example but note the 8000 files.
Would be interesting to add a notebook about processing the XMLs, the code is already available on https://github.com/madewild/CAMille/blob/main/scripts/parse_s3.py

**Comment by madewild** [comment]
I uploaded 51 examples of each (45MB total zipped) on Moodle (UV)

**Comment by devironl** [comment]
> Would be interesting to add a notebook about processing the XMLs

If it is useful for them for creating their own corpus it makes sense. If not I am afraid this is a bit too much for them. What do you think ?

**Comment by madewild** [comment]
Ok forget it then

**Comment by devironl** [comment]
Ok :-)

**Comment by madewild** [comment]
Should I remove the XMLs from the ZIP then?

**Comment by devironl** [comment]
Yes, let's keep it simple :-)
If relevant, we still can add this part next year a bit more in advance

**Comment by madewild** [comment]
Done
