### ISSUE TITLE
module 2 (convert): find a way to add new line between each documents

### ISSUE THREAD

**Issue by devironl** [madewild/tac#54]
`cat` concatenates the files without adding new lines between them. The concatenated corpus is therefore too heavy to process.

Propositions:

- replace `cat` by `awk`: `!awk 1 ../data/txt/*.txt > ../data/all.txt` (but we need to check if it works in Windows)
- use python instead of bash (but we lose the references to bash)

**Comment by madewild** [comment]
Or we add a newline at the end of each text file? Not difficult for me, I could recreate the corpus.

**Comment by devironl** [comment]
Ok ! Let's do that. Is it consistent with the export from the search engine (for the project ?)

**Comment by madewild** [comment]
I can also add a newline on the website exports, it's actually a UNIX best
practice

**Comment by devironl** [comment]
Excellent :-) I close this issue then

**Comment by madewild** [comment]
Well I'll close it when it's done ;)

**Comment by madewild** [comment]
Strange... on Linux if I add newlines, then the file obtained after cat has twice two many lines! Different implementation on Mac?

**Comment by madewild** [comment]
Ah but if I can without the newlines I get the same as you...
```bash
[max@carbon txt]$ cat *.txt > ALL.txt
[max@carbon txt]$ wc ALL.txt 
        0  51086649 312985393 ALL.txt
```

**Comment by madewild** [comment]
OK I found the magic command:

```bash
[max@carbon txt]$ for file in * ; do echo >> $file ; done
[max@carbon txt]$ cat *.txt > ALL.txt
[max@carbon txt]$ wc ALL.txt 
     7936  51094557 312993329 ALL.txt
```

**Comment by madewild** [comment]
(I uploaded the modified corpus on Moodle so you won't need the first line with the students)

**Comment by devironl** [comment]
Great ! Thanks a lot !
